include:
  - infra.yaml
services:
  back:
    container_name: back
    build: .
    ports: 
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
    develop:
      watch:
        - action: sync
          path: .
          target: /app