services:
  postgres:
    container_name: db
    image: postgres
    env_file: ".env"
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: admin
    ports:
      - "5053:5050"
    depends_on:
      - postgres
    env_file: ".env"

  rabbitmq:
    image: rabbitmq:4-management
    container_name: queue
    ports:
     - "5672:5672"
     - "15672:15672"
    env_file: ".env"
    