services:
  postgres:
    container_name: db
    image: postgres
    env_file: ".env"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: admin
    ports:
      - "5053:5050"
    depends_on:
      - postgres
    env_file: ".env"